/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;
import model.Transaction;
import model.User;
import utils.Services;

/**
 *
 * @author user1
 */
public class GUIPandG extends javax.swing.JFrame {

    /**
     * Creates new form GUIPandG
     */
    public GUIPandG() {
        
        initComponents();
        desactiverBoutonsUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        paneMonitoring = new javax.swing.JTabbedPane();
        pnlMonitoring = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMonitoring = new javax.swing.JTextPane();
        btnRenitialiser = new javax.swing.JButton();
        pnlGestTransactions = new javax.swing.JPanel();
        pnlTransactions = new javax.swing.JScrollPane();
        tblTransactions = new javax.swing.JTable();
        btnListeTransactions = new javax.swing.JButton();
        cbRechercher = new javax.swing.JComboBox();
        txtRechercher = new javax.swing.JTextField();
        btnRechercher = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        pnlGestUser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        txtSolde = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNumTel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnSupprimer = new javax.swing.JButton();
        btnAjouter = new javax.swing.JButton();
        btnMAJ = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUtilisateurs = new javax.swing.JTable();
        lblListeUtilisateurs = new javax.swing.JLabel();
        btnAfficherUtilisateurs = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblWarning1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnlConfiguration = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel14.setFont(new java.awt.Font("Thonburi", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 255));
        jLabel14.setText("Park & Go");

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 102, 255));
        jLabel15.setText("Panneau de configuration");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addContainerGap(427, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtMonitoring.setBackground(new java.awt.Color(0, 0, 0));
        txtMonitoring.setForeground(new java.awt.Color(255, 255, 255));
        txtMonitoring.setSelectedTextColor(new java.awt.Color(204, 255, 255));
        txtMonitoring.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(txtMonitoring);

        btnRenitialiser.setForeground(new java.awt.Color(0, 0, 255));
        btnRenitialiser.setText("Réinitialiser");
        btnRenitialiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenitialiserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMonitoringLayout = new javax.swing.GroupLayout(pnlMonitoring);
        pnlMonitoring.setLayout(pnlMonitoringLayout);
        pnlMonitoringLayout.setHorizontalGroup(
            pnlMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMonitoringLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRenitialiser)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        pnlMonitoringLayout.setVerticalGroup(
            pnlMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMonitoringLayout.createSequentialGroup()
                .addGroup(pnlMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMonitoringLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMonitoringLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnRenitialiser)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        paneMonitoring.addTab("Monitoring", pnlMonitoring);

        tblTransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id transaction", "Code emplacement", "Heure début", "Heure fin", "Date", "Username"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        pnlTransactions.setViewportView(tblTransactions);

        btnListeTransactions.setText("Liste transactions");
        btnListeTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeTransactionsActionPerformed(evt);
            }
        });

        cbRechercher.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Code emplacement", "Username" }));

        btnRechercher.setText("Rechercher");
        btnRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGestTransactionsLayout = new javax.swing.GroupLayout(pnlGestTransactions);
        pnlGestTransactions.setLayout(pnlGestTransactionsLayout);
        pnlGestTransactionsLayout.setHorizontalGroup(
            pnlGestTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGestTransactionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGestTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlGestTransactionsLayout.createSequentialGroup()
                        .addComponent(cbRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlGestTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnListeTransactions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRechercher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        pnlGestTransactionsLayout.setVerticalGroup(
            pnlGestTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGestTransactionsLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlGestTransactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRechercher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnListeTransactions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        paneMonitoring.addTab("Gestion des transactions", pnlGestTransactions);

        jLabel1.setText("Username :");

        jLabel2.setText("Password :");

        jLabel3.setText("Nom :");

        jLabel4.setText("Prénom :");

        jLabel5.setText("Solde :");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameKeyReleased(evt);
            }
        });

        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPasswordKeyReleased(evt);
            }
        });

        txtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomActionPerformed(evt);
            }
        });
        txtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomKeyReleased(evt);
            }
        });

        txtPrenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrenomKeyReleased(evt);
            }
        });

        jLabel6.setText("Numéro de Téléphone :");

        jLabel7.setText("Profil de l'utilisateur");

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnMAJ.setText("Mettre à jour");
        btnMAJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMAJActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tblUtilisateurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Nom", "Prénom"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblUtilisateurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUtilisateursMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblUtilisateurs);

        lblListeUtilisateurs.setText("Liste des utilisateurs :");

        btnAfficherUtilisateurs.setText("afficher");
        btnAfficherUtilisateurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfficherUtilisateursActionPerformed(evt);
            }
        });

        jLabel8.setText("Cliquez sur une ligne de la table pour sélectionner ");

        lblWarning1.setText("* : champs obligatoires");

        jLabel9.setText("*");

        jLabel10.setText("*");

        jLabel11.setText("*");

        jLabel12.setText("*");

        jLabel13.setText("un utilisateur ...");

        javax.swing.GroupLayout pnlGestUserLayout = new javax.swing.GroupLayout(pnlGestUser);
        pnlGestUser.setLayout(pnlGestUserLayout);
        pnlGestUserLayout.setHorizontalGroup(
            pnlGestUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGestUserLayout.createSequentialGroup()
                .addGroup(pnlGestUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlGestUserLayout.createSequentialGroup()
                        .addGroup(pnlGestUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlGestUserLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(pnlGestUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlGestUserLayout.createSequentialGroup()
                                        .addGroup(pnlGestUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlGestUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtUsername)
                                            .addComponent(txtPassword)
                                            .addComponent(txtNom)
                                            .addComponent(txtPrenom)
                                            .addComponent(txtSolde)
                                            .addComponent(txtNumTel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(pnlGestUserLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btnAjouter)
                                .addGap(18, 18, 18)
                                .addComponent(btnSupprimer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMAJ)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGestUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGestUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(pnlGestUserLayout.createSequentialGroup()
                                .addComponent(lblListeUtilisateurs)
                                .addGap(18, 18, 18)
                                .addComponent(btnAfficherUtilisateurs)
                                .addGap(0, 91, Short.MAX_VALUE))))
                    .addGroup(pnlGestUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblWarning1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(195, 195, 195)
                        .addGroup(pnlGestUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );
        pnlGestUserLayout.setVerticalGroup(
            pnlGestUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGestUserLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlGestUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlGestUserLayout.createSequentialGroup()
                        .addGroup(pnlGestUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblListeUtilisateurs)
                            .addComponent(btnAfficherUtilisateurs))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlGestUserLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(pnlGestUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGestUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGestUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGestUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGestUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(txtSolde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlGestUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNumTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(pnlGestUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSupprimer)
                            .addComponent(btnMAJ)
                            .addComponent(btnAjouter))))
                .addGap(18, 18, 18)
                .addGroup(pnlGestUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblWarning1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneMonitoring.addTab("Gestion des utilisateurs", pnlGestUser);

        javax.swing.GroupLayout pnlConfigurationLayout = new javax.swing.GroupLayout(pnlConfiguration);
        pnlConfiguration.setLayout(pnlConfigurationLayout);
        pnlConfigurationLayout.setHorizontalGroup(
            pnlConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );
        pnlConfigurationLayout.setVerticalGroup(
            pnlConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        paneMonitoring.addTab("Configuration", pnlConfiguration);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneMonitoring)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(paneMonitoring, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercherActionPerformed
        // TODO add your handling code here:
        String keyword = txtRechercher.getText();
        if(!keyword.equals("")){
            List listeTransactions = Services.rechercherListeTransactions(cbRechercher.getSelectedIndex(), keyword);

            afficherTableTransactions(listeTransactions);
        }
    }//GEN-LAST:event_btnRechercherActionPerformed

    private void btnListeTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeTransactionsActionPerformed
        // TODO add your handling code here:

        List listeTransactions = Services.lireListeTransactions();

        afficherTableTransactions(listeTransactions);
    }//GEN-LAST:event_btnListeTransactionsActionPerformed

    private void btnRenitialiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenitialiserActionPerformed
        // TODO add your handling code here:
        txtMonitoring.setText("");
        contenuTxtMonitoring ="";
    }//GEN-LAST:event_btnRenitialiserActionPerformed

    private void btnAfficherUtilisateursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfficherUtilisateursActionPerformed
        // TODO add your handling code here:
        afficherListeUtilisateurs();
        activerBoutonUsers();
        
    }//GEN-LAST:event_btnAfficherUtilisateursActionPerformed
    private void afficherListeUtilisateurs(){
        
        List listeUtilisateurs = Services.lireListeUtilisateurs();

        afficherTableUtilisateurs(listeUtilisateurs);
    }
    private void tblUtilisateursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUtilisateursMouseClicked
        // TODO add your handling code here:
        int rowIndex = tblUtilisateurs.getSelectedRow();
        String username = (String)tblUtilisateurs.getValueAt(rowIndex, 0); 
        User user = Services.rechercherUtilisateur(username);
        afficherUtilisateur(user);
    }//GEN-LAST:event_tblUtilisateursMouseClicked

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        // TODO add your handling code here:
        User user = new User();
        String userName = txtUsername.getText();
        user.setUserName(userName);
        user.setPassword(txtPassword.getText());
        user.setNom(txtNom.getText());
        user.setPrenom(txtPrenom.getText());
        user.setNumTelephone(txtNumTel.getText());
        try{
            user.setSolde(Double.parseDouble(txtSolde.getText()));
           int err = Services.enregistrerUtilisateur(user);
           switch(err){
               case Services.SUCCESS :resetUsersScr(); JOptionPane.showMessageDialog(null,txtUsername.getText()+" enregistré avec succès", "Information", JOptionPane.INFORMATION_MESSAGE); 
                        afficherListeUtilisateurs();break;
               case Services.CONNECTION_ERROR: JOptionPane.showMessageDialog(null,"L'enregistrement a échoué, \n problème de connexion","Problème de connexion" , err); break;
               case Services.DB_ERROR : JOptionPane.showMessageDialog(null, "Ce nom d'utilisateur n'est pas disponible","Erreur de saisie" , JOptionPane.ERROR_MESSAGE); break;
               default : break;    
           }
          
        }catch(NumberFormatException e){
          JOptionPane.showMessageDialog(null, "Le solde doit être entré en chiffres","Erreur de saisie" , JOptionPane.ERROR_MESSAGE);
        }
       
           
       
        
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        // TODO add your handling code here:

        String userName =txtUsername.getText();
        int err = Services.supprimerUtilisateur(userName);
         switch(err){
           case Services.SUCCESS :resetUsersScr(); JOptionPane.showMessageDialog(null,userName+" a était supprimer avec succès", "Information", JOptionPane.INFORMATION_MESSAGE); 
                    afficherListeUtilisateurs();break;
           case Services.CONNECTION_ERROR: JOptionPane.showMessageDialog(null,"La suupréssion a échoué, \n problème de connexion","Problème de connexion" , err); break;
           case Services.DB_ERROR : JOptionPane.showMessageDialog(null, "Utilisateur inéxistant ","Problème de base de données" , JOptionPane.ERROR_MESSAGE); break;
           default : break;    
       }
        
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnMAJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMAJActionPerformed
        // TODO add your handling code here:
          
         System.out.println(" --1");
         User user = new User();
          System.out.println(" --2");
         String userName = txtUsername.getText();
          System.out.println(" --3");
        user.setUserName(userName);
         System.out.println(" --4");
        user.setPassword(txtPassword.getText());
         System.out.println(" --5");
        user.setNom(txtNom.getText());
         System.out.println(" --6");
        user.setPrenom(txtPrenom.getText());
         System.out.println(" --7");
        user.setNumTelephone(txtNumTel.getText());
        
         try{
           
              user.setSolde(Double.parseDouble(txtSolde.getText()));
        
            int err = Services.updateUtilisateur(user);
                switch(err){
                       case Services.SUCCESS :resetUsersScr(); JOptionPane.showMessageDialog(null,userName+" a était mis-à-jour avec succès", "Information", JOptionPane.INFORMATION_MESSAGE); 
                                afficherListeUtilisateurs();break;
                       case Services.CONNECTION_ERROR: JOptionPane.showMessageDialog(null,"La mise-à-jour a échoué, \n problème de connexion","Problème de connexion" , err); break;
                       case Services.DB_ERROR : JOptionPane.showMessageDialog(null, "Utilisateur inéxistant ","Problème de base de données" , JOptionPane.ERROR_MESSAGE); break;
                       default : break;    
                  }
        }catch(Exception e ){
            JOptionPane.showMessageDialog(null, "Le solde doit être saisie en chiffres ","Erreur de saisie" , JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnMAJActionPerformed
 
    private void txtUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyReleased
        // TODO add your handling code here:
        
       checkInput();
        
    }//GEN-LAST:event_txtUsernameKeyReleased

    private void txtPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyReleased
        // TODO add your handling code here:
        checkInput();
      
    }//GEN-LAST:event_txtPasswordKeyReleased

    private void txtNomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomKeyReleased
        // TODO add your handling code here:
        checkInput();
        
    }//GEN-LAST:event_txtNomKeyReleased

    private void txtPrenomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrenomKeyReleased
        // TODO add your handling code here:
        checkInput();
    }//GEN-LAST:event_txtPrenomKeyReleased
  
    private void checkInput(){
     if(inputOK()){
                     activerBoutonUsers();
            }else{
            
                     desactiverBoutonsUsers();
        }
    
    }
    private boolean inputOK() {
        boolean returnValue = false;
        String username = txtUsername.getText();
        String password = txtPassword.getText();
        String nom = txtNom.getText();
        String prenom = txtPrenom.getText();
        if(!(username.equals("") || password.equals("") || nom.equals("") || prenom.equals(""))){
            returnValue = true;
        }
        
        return returnValue;
    }
    private void desactiverBoutonsUsers(){
    
                     btnAjouter.setEnabled(false);
                     btnSupprimer.setEnabled(false);
                     btnMAJ.setEnabled(false);
                   
    }
    private void activerBoutonUsers(){
    
                     btnAjouter.setEnabled(true);
                     btnSupprimer.setEnabled(true);
                     btnMAJ.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPandG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPandG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPandG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPandG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfficherUtilisateurs;
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnListeTransactions;
    private javax.swing.JButton btnMAJ;
    private javax.swing.JButton btnRechercher;
    private javax.swing.JButton btnRenitialiser;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JComboBox cbRechercher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblListeUtilisateurs;
    private javax.swing.JLabel lblWarning1;
    private javax.swing.JTabbedPane paneMonitoring;
    private javax.swing.JPanel pnlConfiguration;
    private javax.swing.JPanel pnlGestTransactions;
    private javax.swing.JPanel pnlGestUser;
    private javax.swing.JPanel pnlMonitoring;
    private javax.swing.JScrollPane pnlTransactions;
    private javax.swing.JTable tblTransactions;
    private javax.swing.JTable tblUtilisateurs;
    private javax.swing.JTextPane txtMonitoring;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNumTel;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtRechercher;
    private javax.swing.JTextField txtSolde;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    // attributs 
    private String contenuTxtMonitoring ="";

    
    // getteurs et setteurs 
    public String getContenuTxtMonitoring() {
        return contenuTxtMonitoring;
    }

    public void setContenuTxtMonitoring(String contenuTxtMonitoring) {
        this.contenuTxtMonitoring = contenuTxtMonitoring;
    }
    
 
    
    public JTextPane getTxtMonitoring() {
        return txtMonitoring;
    }

    public void setTxtMonitoring(JTextPane txtMonitoring) {
        this.txtMonitoring = txtMonitoring;
    }
    
    // methodes 
    
    public void ajouterContenuMonitoring(String ligne){
        contenuTxtMonitoring += "\n - "+ligne;
        txtMonitoring.setText(contenuTxtMonitoring);
    }

   private void afficherTableTransactions(List listeTransactions) {
       
        Vector donneesTable = new Vector();
        Vector<String> entete = new Vector<String>();
        entete.add("Id transactions");
        entete.add("Code emplacement");
        entete.add("Heure debut");
        entete.add("Heure fin");
        entete.add("Date");
        entete.add("Username");
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat tf = new SimpleDateFormat("hh:mm");

        for (Object object : listeTransactions) {
            Transaction trx = (Transaction) object;
            Vector ligne = new Vector();
            ligne.add(trx.getIdTransaction());
            ligne.add(trx.getCodeEmplacement());
            ligne.add(tf.format(trx.getHeureDebut().getTime()));
            ligne.add(tf.format(trx.getHeureFin().getTime()));
            ligne.add(df.format(trx.getDate().getTime()));
            ligne.add(trx.getUser().getUserName());

            donneesTable.add(ligne);
        }

        tblTransactions.setModel(new DefaultTableModel(donneesTable, entete));

    } 

    private void afficherTableUtilisateurs(List listeUtilisateurs) {
       
        Vector donneesTable = new Vector();
        Vector<String> entete = new Vector<String>();
        entete.add("Username");
        entete.add("Nom");
        entete.add("Prénom");
      

        for (Object object : listeUtilisateurs) {
            User usr = (User) object;
            Vector ligne = new Vector();
            ligne.add(usr.getUserName());
            ligne.add(usr.getNom());
            ligne.add(usr.getPrenom());
            donneesTable.add(ligne);
        }

        tblUtilisateurs.setModel(new DefaultTableModel(donneesTable, entete));
    }

    private void afficherUtilisateur(User user) {
        txtUsername.setText(user.getUserName());
        txtPassword.setText(user.getPassword());
        txtPrenom.setText(user.getPrenom());
        txtNom.setText(user.getNom());
        txtNumTel.setText(user.getNumTelephone());
        txtSolde.setText(new Double(user.getSolde()).toString());
        
    }

    private void resetUsersScr() {
        txtUsername.setText("");
        txtPassword.setText("");
        txtNom.setText("");
        txtPrenom.setText("");
        txtSolde.setText("");
        txtNumTel.setText("");
    }
  
  

}
